/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ApiSpeakersIdPhotoRouteImport } from './routes/api/speakers/$id/photo'
import { Route as ApiGalleryIdThumbRouteImport } from './routes/api/gallery/$id/thumb'
import { Route as ApiGalleryIdAssetKeyRouteImport } from './routes/api/gallery/$id/asset/$key'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakersIdPhotoRoute = ApiSpeakersIdPhotoRouteImport.update({
  id: '/api/speakers/$id/photo',
  path: '/api/speakers/$id/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryIdThumbRoute = ApiGalleryIdThumbRouteImport.update({
  id: '/api/gallery/$id/thumb',
  path: '/api/gallery/$id/thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryIdAssetKeyRoute = ApiGalleryIdAssetKeyRouteImport.update({
  id: '/api/gallery/$id/asset/$key',
  path: '/api/gallery/$id/asset/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/speakers': typeof SpeakersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/gallery/$id/thumb': typeof ApiGalleryIdThumbRoute
  '/api/speakers/$id/photo': typeof ApiSpeakersIdPhotoRoute
  '/api/gallery/$id/asset/$key': typeof ApiGalleryIdAssetKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/speakers': typeof SpeakersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/gallery/$id/thumb': typeof ApiGalleryIdThumbRoute
  '/api/speakers/$id/photo': typeof ApiSpeakersIdPhotoRoute
  '/api/gallery/$id/asset/$key': typeof ApiGalleryIdAssetKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/speakers': typeof SpeakersRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/api/gallery/$id/thumb': typeof ApiGalleryIdThumbRoute
  '/api/speakers/$id/photo': typeof ApiSpeakersIdPhotoRoute
  '/api/gallery/$id/asset/$key': typeof ApiGalleryIdAssetKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/gallery'
    | '/speakers'
    | '/demo/tanstack-query'
    | '/api/gallery/$id/thumb'
    | '/api/speakers/$id/photo'
    | '/api/gallery/$id/asset/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/gallery'
    | '/speakers'
    | '/demo/tanstack-query'
    | '/api/gallery/$id/thumb'
    | '/api/speakers/$id/photo'
    | '/api/gallery/$id/asset/$key'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/gallery'
    | '/speakers'
    | '/demo/tanstack-query'
    | '/api/gallery/$id/thumb'
    | '/api/speakers/$id/photo'
    | '/api/gallery/$id/asset/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  SpeakersRoute: typeof SpeakersRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ApiGalleryIdThumbRoute: typeof ApiGalleryIdThumbRoute
  ApiSpeakersIdPhotoRoute: typeof ApiSpeakersIdPhotoRoute
  ApiGalleryIdAssetKeyRoute: typeof ApiGalleryIdAssetKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speakers/$id/photo': {
      id: '/api/speakers/$id/photo'
      path: '/api/speakers/$id/photo'
      fullPath: '/api/speakers/$id/photo'
      preLoaderRoute: typeof ApiSpeakersIdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/$id/thumb': {
      id: '/api/gallery/$id/thumb'
      path: '/api/gallery/$id/thumb'
      fullPath: '/api/gallery/$id/thumb'
      preLoaderRoute: typeof ApiGalleryIdThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/$id/asset/$key': {
      id: '/api/gallery/$id/asset/$key'
      path: '/api/gallery/$id/asset/$key'
      fullPath: '/api/gallery/$id/asset/$key'
      preLoaderRoute: typeof ApiGalleryIdAssetKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  SpeakersRoute: SpeakersRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ApiGalleryIdThumbRoute: ApiGalleryIdThumbRoute,
  ApiSpeakersIdPhotoRoute: ApiSpeakersIdPhotoRoute,
  ApiGalleryIdAssetKeyRoute: ApiGalleryIdAssetKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
